### ISSUE TITLE
Linux: Build failing during compliing application step

### ISSUE THREAD

**Issue by godofgrunts** [williamsjokvist/cfn-tracker#158]
Trying to build from source on Linux and I get the following error:

```
Compiling application: -seed chosen at random: Igy64+hsVCpDrQOlezgi7g
# github.com/remyoudompheng/bigfft
/tmp/garble-shared3287645007/aup25FJ/ljP_LTtgk4dz.s:7: expected '(', found /
/tmp/garble-shared3287645007/aup25FJ/ljP_LTtgk4dz.s:12: expected '(', found /
/tmp/garble-shared3287645007/aup25FJ/ljP_LTtgk4dz.s:16: expected '(', found /
/tmp/garble-shared3287645007/aup25FJ/ljP_LTtgk4dz.s:21: expected '(', found /
/tmp/garble-shared3287645007/aup25FJ/ljP_LTtgk4dz.s:25: expected '(', found /
/tmp/garble-shared3287645007/aup25FJ/ljP_LTtgk4dz.s:29: expected '(', found /
/tmp/garble-shared3287645007/aup25FJ/ljP_LTtgk4dz.s:33: expected '(', found /
/tmp/garble-shared3287645007/aup25FJ/ljP_LTtgk4dz.s:37: expected '(', found /
asm: assembly of /tmp/garble-shared3287645007/aup25FJ/ljP_LTtgk4dz.s failed
```

I'm not sure how that error is happening though, because this is what that tmp file contains:

```
// Trampolines to math/big assembly implementations.

#include "textflag.h"

// func addVV(z, x, y []Word) (c Word)
TEXT ·i5InR5cT(SB),NOSPLIT,$0
	JMP	math/big·oA16bI6(SB)

// func subVV(z, x, y []Word) (c Word)
// (same as addVV except for SBBQ instead of ADCQ and label names)
TEXT ·o8eL3KEXM(SB),NOSPLIT,$0
	JMP	math/big·_mp126nST(SB)

// func addVW(z, x []Word, y Word) (c Word)
TEXT ·lSPpo9x(SB),NOSPLIT,$0
	JMP	math/big·swisKb9Ed6(SB)

// func subVW(z, x []Word, y Word) (c Word)
// (same as addVW except for SUBQ/SBBQ instead of ADDQ/ADCQ and label names)
TEXT ·iTe68FltK(SB),NOSPLIT,$0
	JMP	math/big·h4iUT1(SB)

// func shlVU(z, x []Word, s uint) (c Word)
TEXT ·_Ddj6f(SB),NOSPLIT,$0
	JMP	math/big·i5cebiu0(SB)

// func shrVU(z, x []Word, s uint) (c Word)
TEXT ·pMenSZ(SB),NOSPLIT,$0
	JMP	math/big·kLpzdkGc2(SB)

// func mulAddVWW(z, x []Word, y, r Word) (c Word)
TEXT ·sMu7QtvjH(SB),NOSPLIT,$0
	JMP	math/big·bJx7X7jhiu(SB)

// func addMulVVW(z, x []Word, y Word) (c Word)
TEXT ·xWMaWNt_v4H(SB),NOSPLIT,$0
	JMP	math/big·mmchSr1JVM5m(SB)
```

**Comment by godofgrunts** [comment]
Just for giggles I disabled obfuscation in `wails.json` and `wails.node.json` and it did build successfully.

**Comment by godofgrunts** [comment]
Although after launching the program it seems to be stuck

![image](https://github.com/user-attachments/assets/21719c84-5526-4bcb-87ae-1e277f32c74c)

**Comment by williamsjokvist** [comment]
Hi, yeah obfuscation isn't working well for mac and linux. It's not in prod only on master. 

Regarding getting stuck, just to make sure, did you enter your credentials in `.env` in the project root with these variables: [example.env](https://github.com/williamsjokvist/cfn-tracker/blob/master/example.env)?

**Comment by williamsjokvist** [comment]
You could try setting `HEADLESS=false` in the .env file, it will spawn the browser window that normally runs in the background. Maybe that can clue us in to whats happening here

**Comment by godofgrunts** [comment]
Can't read Japanese but
![Screenshot from 2024-07-29 12-30-12](https://github.com/user-attachments/assets/af469b41-bb74-49e7-b352-33e7ebffdd9b)

**Comment by godofgrunts** [comment]
I wonder if this is an issue because my password has special characters in it? If I copy my password out of the file and paste it in it works and brings me to the "one time code" page. After I put in my one time code the application starts working.
![image](https://github.com/user-attachments/assets/5ad4f626-bcd8-467b-9cbf-aa5dd167819d)

**Comment by williamsjokvist** [comment]
The error message says `The email address or password is incorrect.`. I guess it could be certain special characters, i have `{`, `]`, `*` in mine without issue.

**Comment by godofgrunts** [comment]
Hmm. I have a `!`,`$`,`*`, and `%` in mine.

**Comment by godofgrunts** [comment]
So with my new password with no special characters it gets to the MFA screen so there is some issue there with the password, but now there's an issue with doing the MFA.

**Comment by williamsjokvist** [comment]
Aha, the bot definitely doesn't support passing the MFA check
