### ISSUE TITLE
Improve UX when failing to start go-rod browser

### ISSUE THREAD

**Issue by tifye** [williamsjokvist/cfn-tracker#46]
Right now the program the panics and the user is left wondering what the hell happened. Maybe could keep the program open but display and error or something similar. Could also be useful to look into how we can get  a hold of some logs.

**Comment by williamsjokvist** [comment]
Ideally we want to show a separate GUI prompt with an error message when the app init fails (db fails, browser fails etc.)

**Comment by williamsjokvist** [comment]
Example frameworks using platform native UI:

- https://github.com/mojbro/gocoa (Mac Cocoa, might not work with Apple Silicon)
- https://github.com/lxn/win / https://github.com/rodrigocfd/windigo Win32
- https://gist.github.com/nathan-osman/18c2e227ad00a223b61c0b3c16d452c3 Win 32

Or we just use wails
